apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "webserver.fullname" .}}
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo I am a cronjob that runs every two minutes
          restartPolicy: OnFailure
